### PR TITLE
Update jQuery load call to use .on()

### PR DESCRIPTION
**Pull request by ryanjafari**
v4.0.2 (for use with Bootstrap 3) was throwing a JS console error when loading a lightbox with an image in it; error described in this Stack article. Using .on('load') instead of .load resolves it.

### CODE REVIEW

**Comment by ashleydw** [comment]
Great! For some reason, I can't see the "Files changed" in the PR. Can you confirm it was just this 1 commit? https://github.com/ashleydw/lightbox/pull/229/commits/1f79fca7dea6a6bbe796b78d0bcc9fecd156d0d5

**Comment by ryanjafari** [comment]
That's correct Ashley. The other commit you see there, https://github.com/ashleydw/lightbox/pull/229/commits/86d8de213a73f40e38a309431ee18245e7c10d9f, is a merge commit that is blank. I believe you ended up removing the files I changed, so the merge commit was cleanly merged in, as the only "conflicts" were that those files were removed in future versions. I just made sure to acknowledge the removal in that merge commit, so it shows nothing.

**Comment by ashleydw** [comment]
Try v5.1.0 which is now BS3 compatible

**Comment by ryanjafari** [comment]
Ryan Jafari liked your email
Spark by Readdle
Spark by Readdle

**Pull request closed without merging**
